### ISSUE TITLE
About ResultTuple.sequence implementation (and the general API)

### ISSUE THREAD

**Issue by xvw** [fewlinesco/kaur#1]
The ResultTuple module exposes a specific data structure, in my opinion, so it needs functions such as `ok?` and `error?`.
With these two functions, sequence could be rewritten using https://hexdocs.pm/elixir/Enum.html#reduce_while/3

**Comment by tgautier** [comment]
Good find!

**Comment by xvw** [comment]
In fact, I think the "best" approach would be to implement a protocol. Because `and_then` is only` flat_map`. And we could implement sympatic combinators (like `or_else` or` kleisli variation`), and deal with nil.

**Comment by kdisneur** [comment]
Fixed by #3
