### ISSUE TITLE
Implement a Kaur.GenServerResult to generate handle_call responses

### ISSUE THREAD

**Issue by Betree** [fewlinesco/kaur#30]
Hey Kaur's team, your lib is great and brought very nice syntax improvements to [our code](https://github.com/CaptainFact). I'd like to be able to reproduce the behavior of `Kaur.Result` to deal with GenServer responses, which would also be great to handle Phoenix's websockets responses.

A GenServer `handle_call` function must returns a tuple like:
```elixir
{:reply, reply, new_state}
```

While the `handle_cast` function must return:
```elixir
{:reply, new_state}
```

Full documentation here : https://elixir-lang.org/getting-started/mix-otp/genserver.html

# Proposition

It would be nice to be able to pipe results and generate 

```elixir
iex> data
     |> ...()
     |> Kaur.GenServerResult.reply("response", %{})

{:reply, "response", %{}}
```

Would you be interested in such a PR  ?

**Comment by yordis** [comment]
What would be the benefit of this?

**Comment by Betree** [comment]
@yordis Never mind, it was related to a business-specific need. Not a real feature.
